### ISSUE TITLE
[BUG] Repo incompatible with Python 3.12.7 (ARM64) & 3.11.8 (ARM64).  Lower versions of Python for Windows aren't available for ARM64. - Snapdragon X Elite has no native working version.

### ISSUE THREAD

**Issue by BrickDesignerNL** [quic/ai-hub-models#113]
**Describe the bug**
Just got my new Lenovo Yoga 7 with Qualcomm X Elite and 32GB RAM.
Trying to install this repo using Python 3.12.7 on CMD.

I get lots of errors mainly due to dependencies that try to use removed features. This makes this repo not compatible with Python 3.12.

**I have installed**
Visual Studio Community version, ARM edition, Desktop C++ fully installed.
Python 3.12.7 installed
Pip 24.3.1 installed

And run:
*python -m pip install setuptools*
This fixed some issues.

**The process now breaks at**
python -m pip install opencv-python
=>       AttributeError: module 'pkgutil' has no attribute 'ImpImporter'.
That has been removed from pkgutil.

**Expected behavior**
I actually expected that I just had to run the commands given in the readme.

But those are Linux command  (the && doesn't work : "source" does not exits; I just ran the activate.bat in the Script folder).
And some dependencies don't work under 3.12.7.

**My request**
Since 3.10 and lower can't be downloaded for ARM64 (anymore) from python.org (ref: https://www.python.org/downloads/windows/ ), can you upgrade this repo so that it will work on 3.12 and up.
If you can provide Windows CMD instructions next to the Linux instructions it would be great; Linux is not yet available fully functional on X1E-78-100 laptops, and these devices typically come with Windows 11.
I see some dependencies like *NumPy* (ref: https://pypi.org/project/numpy/) and *PyTorch-NPU* (ref: https://pypi.org/project/torch-npu/) [might be good to add for Snapdragon X Elite next to PyTorch] have been updated , so I it might be beneficial for the execution performance to look if those can be updated too.

**Stack trace**
(qai_hub_models_env) C:\Users\\<user_name>\python\qai_hub_models_env>pip install opencv-python
Collecting opencv-python
  Using cached opencv-python-4.10.0.84.tar.gz (95.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\\<user_name>\python\qai_hub_models_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\\<user_name>\python\qai_hub_models_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\\<user_name>\python\qai_hub_models_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\\<user_name>\python\qai_hub_models_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\\<user_name>\AppData\Local\Programs\Python\Python312-arm64\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\\<user_name>\AppData\Local\Temp\pip-build-env-1gnu2uwg\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\\<user_name>\AppData\Local\Temp\pip-build-env-1gnu2uwg\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\\<user_name>\AppData\Local\Temp\pip-build-env-1gnu2uwg\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Host configuration:**
 - OS and version: Windows 11 ARM64 => CMD
 - I want to run the models locally on the NPU/GPU of the laptop.
 - Lenovo Yoga 7 with Qualcomm X Elite and 32GB RAM (15,7GB shared NPU/GPU)

Thank you, I'm looking forward to use this HUB!
Funny by the way that your team is called QUIC.
I was directly thinking of https://en.wikipedia.org/wiki/QUIC while that was is innovative at the time (now part of TLS 1.3), but in a totally different area of expertise :)

**Comment by BrickDesignerNL** [comment]
**Reproduction**
C:\Users\<user_name>\python>py -m venv qai_hub_models_env

C:\Users\<user_name>\python>py -3.11 -m venv C:\Users\<user_name>\python\qai_hub_models_env

C:\Users\<user_name>\python>cd C:\Users\<user_name>\python\qai_hub_models_env\Scripts

C:\Users\<user_name>\python\qai_hub_models_env\Scripts>activate

(qai_hub_models_env) C:\Users\<user_name>\python\qai_hub_models_env\Scripts>cd ..

(qai_hub_models_env) C:\Users\<user_name>\python\qai_hub_models_env>py --version
Python 3.11.8

(qai_hub_models_env) C:\Users\<user_name>\python\qai_hub_models_env>py -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\<user_name>\python\qai_hub_models_env\lib\site-packages (24.0)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-24.3.1

(qai_hub_models_env) C:\Users\<user_name>\python\qai_hub_models_env>py -m pip install qai_hub_models
Collecting qai_hub_models
  Using cached qai_hub_models-0.17.0-py3-none-any.whl.metadata (56 kB)
Collecting Pillow<12,>10 (from qai_hub_models)
  Using cached pillow-11.0.0-cp311-cp311-win_arm64.whl.metadata (9.3 kB)
Collecting gdown==4.7.1 (from qai_hub_models)
  Using cached gdown-4.7.1-py3-none-any.whl.metadata (4.4 kB)
Collecting gitpython==3.1.42 (from qai_hub_models)
  Using cached GitPython-3.1.42-py3-none-any.whl.metadata (12 kB)
Collecting huggingface-hub<0.24,>=0.23.1 (from qai_hub_models)
  Using cached huggingface_hub-0.23.5-py3-none-any.whl.metadata (12 kB)
Collecting ipython==8.12.3 (from qai_hub_models)
  Using cached ipython-8.12.3-py3-none-any.whl.metadata (5.7 kB)
Collecting numpy<2,>=1.23.5 (from qai_hub_models)
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting onnx<1.17,>=1.14.1 (from qai_hub_models)
  Using cached onnx-1.16.2.tar.gz (12.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting opencv-python<5,>4 (from qai_hub_models)
  Using cached opencv-python-4.10.0.84.tar.gz (95.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas<2.3,>=1.4.3 (from qai_hub_models)
  Using cached pandas-2.2.3.tar.gz (4.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting prettytable==3.11.0 (from qai_hub_models)
  Using cached prettytable-3.11.0-py3-none-any.whl.metadata (30 kB)
Collecting pyyaml==6.0.2 (from qai_hub_models)
  Using cached pyyaml-6.0.2.tar.gz (130 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests-toolbelt==1.0.0 (from qai_hub_models)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting schema==0.7.5 (from qai_hub_models)
  Using cached schema-0.7.5-py2.py3-none-any.whl.metadata (34 kB)
INFO: pip is looking at multiple versions of qai-hub-models to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.0.0 Requires-Python >=3.8, <3.11; 0.10.0 Requires-Python <3.11,>=3.8; 0.11.0 Requires-Python <3.11,>=3.8; 0.11.1 Requires-Python <3.11,>=3.8; 0.11.2 Requires-Python <3.11,>=3.8; 0.11.3 Requires-Python <3.11,>=3.8; 0.11.4 Requires-Python <3.11,>=3.8; 0.12.0 Requires-Python <3.11,>=3.8; 0.12.1 Requires-Python <3.11,>=3.8; 0.12.2 Requires-Python <3.11,>=3.8; 0.13.0 Requires-Python <3.11,>=3.8; 0.14.0 Requires-Python <3.11,>=3.8; 0.15.0 Requires-Python <3.11,>=3.8; 0.16.2 Requires-Python <3.11,>=3.8; 0.2.0 Requires-Python >=3.8, <3.11; 0.2.1 Requires-Python >=3.8, <3.11; 0.2.2 Requires-Python >=3.8, <3.11; 0.2.3 Requires-Python >=3.8, <3.11; 0.2.5 Requires-Python >=3.8, <3.11; 0.2.6 Requires-Python >=3.8, <3.11; 0.2.7 Requires-Python >=3.8, <3.11; 0.2.71 Requires-Python >=3.8, <3.11; 0.3.0 Requires-Python >=3.8, <3.11; 0.3.1 Requires-Python >=3.8, <3.11; 0.3.2 Requires-Python >=3.8, <3.11; 0.4.0 Requires-Python >=3.8, <3.11; 0.4.1 Requires-Python <3.11,>=3.8; 0.5.0 Requires-Python <3.11,>=3.8; 0.5.1 Requires-Python <3.11,>=3.8; 0.6.0 Requires-Python <3.11,>=3.8; 0.7.0 Requires-Python <3.11,>=3.8; 0.8.0 Requires-Python <3.11,>=3.8; 0.9.0 Requires-Python <3.11,>=3.8; 0.9.2 Requires-Python <3.11,>=3.8; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement torch<2.5.0,>=2.1.2 (from qai-hub-models) (from versions: none)
ERROR: No matching distribution found for torch<2.5.0,>=2.1.2

**Comment by BrickDesignerNL** [comment]
### Work-a-round

## WARNING
This uses a python version that has **_known security issues_** and has not been updated since April 5th, 2023.
https://peps.python.org/pep-0619/#source-only-security-fix-releases

## Installation instruction**

# Visual Studio
Install Visual Studio https://visualstudio.microsoft.com/vs/ latest version, install older versions.
Install at least "Desktop C++"

# Python 3.10.11 for x86_64
Install this version of Python https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe that can be found on https://www.python.org/downloads/windows/ - while installing, check the box to add it to the PATH.

# Command line

**Follow these instructions:**
- start Windows command line:  cmd.exe
- at the command line execute the commands below one by one, but not before you replace <user_name> in the command below by your own local windows username:
  - py -m venv qai_hub_models_env_py310
  - py -3.10 -m venv C:\Users\<user_name>\python\qai_hub_models_env_py310
  - cd C:\Users\<user_name>\python\qai_hub_models_env_py310\Scripts
  - activate
  - cd ..
  - py --version
  - py -m pip install --upgrade pip
  - py -m pip install qai_hub_models



## WARNING
This uses a python version that has **_known security issues_** and has not been updated since April 5th, 2023.
https://peps.python.org/pep-0619/#source-only-security-fix-releases
handle accordingly.

**Comment by kory** [comment]
Hi there,

Thank you for your report.

Per our README, ARM python is explicitly not supported on Windows. You'll need to install AMD64 python for support. If AMD64 is failing to install on Python 3.11 or 3.12, please let us know. That path is well-tested internally via our CI.

**Comment by kory** [comment]
We are not in control of ARM64 support at this time because we depend on several packages that do not yet distribute binaries for it. As you pasted above, torch is the biggest dependency we're waiting on.

**Comment by BrickDesignerNL** [comment]
Hi Kort, thank you for your replies.
In the readme I overlooked the not support for ARM64 python, due to I read support for Qualcomm X Elite, and that is ARM64.

I also read most models need 3.10 so that's why after trying and failing 12 and 11 on ARM64 and seeing them fail on removed functions (needing python -m pip install setuptools while that was not in the readme), I assumed 3.12 was not working at all yet.

So that's why I started installing 3.10 amd64 in the way described above.
I didn't got any model running on it though.

Would be great if the readme could be extended a bit for Windows X Elite users.
I almost thrown in the towel and was thinking of returning the laptop to get an Intel.
So thanks for this feedback, I'll try 3.12 amd64.
